name: Build Game
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Unity
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: WebGL
